(() => {
'use strict';
const CFG={CHAIN_ID:'cosmoshub-4',FEE_DENOM:'uatom',FEE_GAS_PRICE:.025,ESCROW:'cosmos1rzsxsv2vf0k2tnejntmvencrq3jxwqhqwh3584plmwgs5sycvn6qa28fvw',PUSDC_VAULT:'cosmos1fttnv5psznxvpm52m3vk3c8tej9e350g40vxktvcxrz50y3apjpq07cuj4',PUSDC_NFT:'cosmos1l7gw3rpuh623sk50njrfgjucrv4k33q8f50t8j96wqzrkm6l54ys246uyt',ADMIN:'cosmos1mn2ekfxs8zc40hdjt44edfaht0pdgquluzrs2j',REST:['https://cosmos-rest.publicnode.com','https://rest.cosmos.directory/cosmoshub','https://cosmos-api.polkachu.com'],GAS:{sendNft:650000,escrowExecute:650000},ROLE_MAP:{'1000000':{label:'$1',role:'Surface Drifter',game:'Scavenger',fate:'Vanished in the Fields'},'5000000':{label:'$5',role:'Ration Runner',game:'Supply Runner',fate:'Supply Line Collapse'},'10000000':{label:'$10',role:'Signal Scout',game:'Recon / Drone Scout',fate:'Signal Lost'},'20000000':{label:'$20',role:'Tunnel Watcher',game:'Defender',fate:'Corridor Breach'},'50000000':{label:'$50',role:'Silo Hand',game:'Engineer',fate:'Power Surge Fatality'},'100000000':{label:'$100',role:'Blast Door Guard',game:'Heavy Defender',fate:'Last Stand at the Door'},'500000000':{label:'$500',role:'Launch Control',game:'Commander',fate:'Systems Failure'},'1000000000':{label:'$1000',role:'Missileer',game:'Legendary Operator',fate:'Final Sacrifice'}}};
const $=id=>document.getElementById(id),enc=new TextEncoder();let state={wallet:null,walletType:null,pubKey:null,escrowConfig:null,escrowState:null,walletTokens:[],escrowDeposit:null,selectedAvailable:new Set(),selectedEscrow:new Set()};
const short=a=>a?a.slice(0,10)+'…'+a.slice(-8):'—'; const fmtMicro=u=>'$'+(Number(u||0)/1e6).toLocaleString(undefined,{maximumFractionDigits:6});
function toast(msg,type='ok'){const el=$('toast');el.textContent=msg;el.style.borderLeftColor=type==='err'?'#ef4444':'#ff3b24';el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),4600)}
function toB64(u8){let s='';for(let i=0;i<u8.length;i++)s+=String.fromCharCode(u8[i]);return btoa(s)} function fromB64(b){let s=atob(b),u=new Uint8Array(s.length);for(let i=0;i<s.length;i++)u[i]=s.charCodeAt(i);return u} function jsonB64(obj){return btoa(unescape(encodeURIComponent(JSON.stringify(obj))))}
class PW{constructor(){this.c=[]}v(n){let b=[];if(typeof n==='bigint'){while(n>127n){b.push(Number(n&0x7fn)|128);n>>=7n}b.push(Number(n))}else{n=Math.floor(Number(n));while(n>127){b.push((n&127)|128);n=Math.floor(n/128)}b.push(n&127)}this.c.push(new Uint8Array(b));return this}t(f,w){return this.v((f<<3)|w)}s(f,str){if(str===undefined||str===null)return this;str=String(str);if(!str.length)return this;const e=enc.encode(str);this.t(f,2).v(e.length);this.c.push(e);return this}b(f,arr){if(!arr||!arr.length)return this;const u=arr instanceof Uint8Array?arr:new Uint8Array(arr);this.t(f,2).v(u.length);this.c.push(u);return this}u64(f,n){const bn=typeof n==='bigint'?n:BigInt(Math.floor(Number(n)));if(bn===0n)return this;return this.t(f,0).v(bn)}fin(){let total=this.c.reduce((a,x)=>a+x.length,0),out=new Uint8Array(total),p=0;for(const x of this.c){out.set(x,p);p+=x.length}return out}}
const coin=(denom,amount)=>new PW().s(1,denom).s(2,String(amount)).fin(); function encodeMsgExecute(sender,contract,msgObj,funds){const pw=new PW().s(1,sender).s(2,contract).b(3,enc.encode(JSON.stringify(msgObj)));(funds||[]).forEach(c=>pw.b(5,coin(c.denom,c.amount)));return pw.fin()} const anyMsg=(typeUrl,value)=>new PW().s(1,typeUrl).b(2,value).fin(); const txBody=msgBytes=>new PW().b(1,anyMsg('/cosmwasm.wasm.v1.MsgExecuteContract',msgBytes)).fin(); const signerInfoDirect=(pk,seq)=>new PW().b(1,anyMsg('/cosmos.crypto.secp256k1.PubKey',new PW().b(1,pk).fin())).b(2,new PW().b(1,new PW().u64(1,1n).fin()).fin()).u64(3,seq).fin(); const feeMsg=(amount,gas)=>new PW().b(1,coin(CFG.FEE_DENOM,amount)).u64(2,BigInt(gas)).fin(); const authInfoDirect=(pk,seq,fee,gas)=>new PW().b(1,signerInfoDirect(pk,seq)).b(2,feeMsg(fee,gas)).fin(); const txRaw=(body,auth,sig)=>new PW().b(1,body).b(2,auth).b(3,sig).fin();
async function restFetch(path,opts){let last;for(const base of CFG.REST){try{const r=await fetch(base+path,opts);if(!r.ok){last=new Error(base+' '+r.status);continue}return await r.json()}catch(e){last=e}}throw last||new Error('All REST endpoints failed')} async function queryContract(contract,query){const q=btoa(JSON.stringify(query));const d=await restFetch('/cosmwasm/wasm/v1/contract/'+contract+'/smart/'+q);return d.data}
async function getAccount(addr){const d=await restFetch('/cosmos/auth/v1beta1/accounts/'+addr);let acc=d.account||d;for(let i=0;i<6&&acc;i++){if(acc.base_vesting_account)acc=acc.base_vesting_account.base_account||acc.base_vesting_account;else if(acc.base_account)acc=acc.base_account;else break}return{accountNumber:BigInt(acc.account_number||0),sequence:BigInt(acc.sequence||0)}} async function broadcast(rawBytes){for(const base of CFG.REST){try{const r=await fetch(base+'/cosmos/tx/v1beta1/txs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tx_bytes:toB64(rawBytes),mode:'BROADCAST_MODE_SYNC'})});if(!r.ok)continue;const j=await r.json(),res=j.tx_response||j;return{code:Number(res.code||0),txhash:res.txhash||'',rawLog:res.raw_log||''}}catch(e){}}throw new Error('Broadcast failed on all REST endpoints')}
function activeWallet(){return state.walletType==='keplr'?window.keplr:state.walletType==='leap'?window.leap:null} async function signAndBroadcast(contract,msg,funds,gas){if(!state.wallet||!state.pubKey)throw new Error('Connect wallet first');const msgBytes=encodeMsgExecute(state.wallet,contract,msg,funds||[]),body=txBody(msgBytes),acct=await getAccount(state.wallet),feeAmount=String(Math.ceil(gas*CFG.FEE_GAS_PRICE)),auth=authInfoDirect(state.pubKey,acct.sequence,feeAmount,gas),wallet=activeWallet();if(!wallet||!wallet.signDirect)throw new Error('Wallet does not support signDirect');toast('Awaiting wallet signature…');const resp=await wallet.signDirect(CFG.CHAIN_ID,state.wallet,{bodyBytes:body,authInfoBytes:auth,chainId:CFG.CHAIN_ID,accountNumber:String(acct.accountNumber)});const raw=txRaw(resp.signed.bodyBytes,resp.signed.authInfoBytes,fromB64(resp.signature.signature));toast('Broadcasting transaction…');const res=await broadcast(raw);if(res.code!==0)throw new Error('Chain error '+res.code+': '+res.rawLog);return res}
async function connectWallet(kind){const wallet=kind==='keplr'?window.keplr:window.leap;if(!wallet){toast(kind+' not found','err');return}await wallet.enable(CFG.CHAIN_ID);const offline=wallet.getOfflineSigner(CFG.CHAIN_ID),accounts=await offline.getAccounts();if(!accounts||!accounts[0])throw new Error('No account returned');state.wallet=accounts[0].address;state.pubKey=accounts[0].pubkey;state.walletType=kind;localStorage.setItem('missileer_wallet',kind);$('walletModal').classList.add('hidden');toast('Wallet connected');await refreshAll()}
function roleForAmount(amount){return CFG.ROLE_MAP[String(amount)]||{label:fmtMicro(amount),role:'Unknown Role',game:'Unknown',fate:'Unknown'}}
async function refreshEscrowState(){try{const [cfg,st]=await Promise.all([queryContract(CFG.ESCROW,{config:{}}),queryContract(CFG.ESCROW,{state:{}})]);state.escrowConfig=cfg;state.escrowState=st;renderEscrowStatus()}catch(e){console.error(e);toast('Could not load MISSILEER escrow state','err')}} function renderEscrowStatus(){const cfg=state.escrowConfig||{},st=state.escrowState||{},activated=!!cfg.project_activated,supply=st.active_escrowed_value||'0',door=activated?'SEALED':'OPEN';$('doorStatus').textContent='BLAST DOOR '+door;$('doorSub').textContent=activated?'Project activated. Depositor withdrawals are closed.':'Withdrawals open until first project payment.';$('heroDoor').textContent=door;$('heroSupply').textContent=fmtMicro(supply);$('siloSupply').textContent=fmtMicro(supply);$('siloSupplyRaw').textContent=String(supply||'0')+' micro-USDC';$('tickerDoor').textContent=door;$('tickerDoor2').textContent=door}
async function refreshWalletUi(){if(!state.wallet){$('walletShort').textContent='Not connected';$('walletFull').textContent='Connect Keplr or Leap';$('adminPanel').style.display='none';return}$('walletShort').textContent=short(state.wallet);$('walletFull').textContent=state.wallet;$('adminPanel').style.display=state.wallet===CFG.ADMIN?'block':'none'}
async function getVaultInfo(tokenId){try{return await queryContract(CFG.PUSDC_VAULT,{vault_info:{token_id:tokenId}})}catch(e){return null}}
async function scanWalletPusdc(){if(!state.wallet){$('walletModal').classList.remove('hidden');return}$('availableGrid').innerHTML='<div class="empty">Scanning wallet pUSDC NFTs...</div>';let tokens=[];try{const res=await queryContract(CFG.PUSDC_NFT,{tokens:{owner:state.wallet,start_after:null,limit:100}});tokens=res.tokens||[]}catch(e){console.error(e);toast('Could not scan wallet pUSDC','err');return}const rows=[];for(const tokenId of tokens){const vi=await getVaultInfo(tokenId);if(vi&&!vi.redeemed)rows.push({tokenId,vault:vi})}state.walletTokens=rows;renderAvailableTokens()}
function tokenCardHtml(tokenId,amount,status,group){const role=roleForAmount(amount);return `<article class="nft-card" data-token="${escapeHtml(tokenId)}" data-group="${group}"><span class="status">${escapeHtml(status)}</span><small>${escapeHtml(tokenId)}</small><div class="amount">${escapeHtml(role.label)}</div><h4>${escapeHtml(role.role)}</h4><div class="role">${escapeHtml(role.game)}</div><small>Possible fate: ${escapeHtml(role.fate)}</small></article>`}
function renderAvailableTokens(){const grid=$('availableGrid');state.selectedAvailable.clear();updateSelectedLabels();if(!state.walletTokens.length){grid.innerHTML='<div class="empty">No active wallet-held pUSDC NFTs found.</div>';return}grid.innerHTML=state.walletTokens.map(r=>tokenCardHtml(r.tokenId,r.vault.usdc_amount,'Wallet-held pUSDC','available')).join('')}
async function refreshMyEscrow(){if(!state.wallet){$('walletModal').classList.remove('hidden');return}try{const d=await queryContract(CFG.ESCROW,{deposit:{owner:state.wallet}});state.escrowDeposit=d;await renderEscrowTokens()}catch(e){console.error(e);$('escrowGrid').innerHTML='<div class="empty">No escrow record found.</div>'}}
async function renderEscrowTokens(){const grid=$('escrowGrid');state.selectedEscrow.clear();updateSelectedLabels();const active=(state.escrowDeposit&&state.escrowDeposit.active_token_ids)||[];if(!active.length){grid.innerHTML='<div class="empty">No active escrowed pUSDC for this wallet.</div>';return}const rows=[];for(const tokenId of active){try{const t=await queryContract(CFG.ESCROW,{escrowed_token:{token_id:tokenId}});if(t)rows.push(t)}catch(e){}}grid.innerHTML=rows.length?rows.map(r=>tokenCardHtml(r.token_id,r.usdc_amount,'Supplied to Silo','escrow')).join(''):'<div class="empty">No active escrowed pUSDC details found.</div>'}
async function supplySelected(){if(!state.wallet){$('walletModal').classList.remove('hidden');return}if(!state.selectedAvailable.size){toast('Select pUSDC to supply first','err');return}const ids=Array.from(state.selectedAvailable);for(const tokenId of ids){const hook=jsonB64({deposit:{referral_code:null}}),msg={send_nft:{contract:CFG.ESCROW,token_id:tokenId,msg:hook}},res=await signAndBroadcast(CFG.PUSDC_NFT,msg,[],CFG.GAS.sendNft);toast('Supplied '+tokenId+': '+res.txhash)}setTimeout(refreshAll,5000)}
async function withdrawSelected(){if(!state.wallet){$('walletModal').classList.remove('hidden');return}if(!state.selectedEscrow.size){toast('Select escrowed pUSDC to retrieve first','err');return}if(state.escrowConfig&&state.escrowConfig.project_activated){toast('Project activated. Depositor withdrawals are closed.','err');return}const ids=Array.from(state.selectedEscrow),msg={withdraw_before_activation:{token_ids:ids}},res=await signAndBroadcast(CFG.ESCROW,msg,[],CFG.GAS.escrowExecute);toast('Retrieved pUSDC: '+res.txhash);setTimeout(refreshAll,5000)}
async function releaseSelected(){if(state.wallet!==CFG.ADMIN){toast('Admin only','err');return}if(!state.selectedEscrow.size){toast('Select escrowed pUSDC to release first','err');return}if(($('activateConfirm').value||'').trim()!=='ACTIVATE MISSILEER'){toast('Type ACTIVATE MISSILEER to confirm first project payment','err');return}const ids=Array.from(state.selectedEscrow),msg={release_to_treasury:{token_ids:ids,memo:'MISSILEER project payment from Mission Control'}},res=await signAndBroadcast(CFG.ESCROW,msg,[],CFG.GAS.escrowExecute);toast('Treasury release broadcast: '+res.txhash);setTimeout(refreshAll,5000)}
function updateSelectedLabels(){$('selectedAvailableLabel').textContent=state.selectedAvailable.size?state.selectedAvailable.size+' wallet pUSDC selected.':'No pUSDC selected.';$('selectedEscrowLabel').textContent=state.selectedEscrow.size?state.selectedEscrow.size+' escrowed pUSDC selected.':'No escrowed pUSDC selected.'}
function bindUi(){$('connectTopBtn').onclick=()=>$('walletModal').classList.remove('hidden');$('closeWalletModal').onclick=()=>$('walletModal').classList.add('hidden');$('keplrBtn').onclick=()=>connectWallet('keplr').catch(e=>{console.error(e);toast(e.message,'err')});$('leapBtn').onclick=()=>connectWallet('leap').catch(e=>{console.error(e);toast(e.message,'err')});$('scanBtn').onclick=scanWalletPusdc;$('refreshEscrowBtn').onclick=refreshMyEscrow;$('supplySelectedBtn').onclick=()=>supplySelected().catch(e=>{console.error(e);toast(e.message,'err')});$('withdrawSelectedBtn').onclick=()=>withdrawSelected().catch(e=>{console.error(e);toast(e.message,'err')});$('releaseSelectedBtn').onclick=()=>releaseSelected().catch(e=>{console.error(e);toast(e.message,'err')});document.addEventListener('click',e=>{const card=e.target.closest('.nft-card[data-token]');if(!card)return;const token=card.dataset.token,group=card.dataset.group,set=group==='available'?state.selectedAvailable:state.selectedEscrow;if(set.has(token)){set.delete(token);card.classList.remove('selected')}else{set.add(token);card.classList.add('selected')}updateSelectedLabels()})}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function bindReveal(){const els=document.querySelectorAll('.reveal'),io=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');io.unobserve(entry.target)}})},{threshold:.12});els.forEach(el=>io.observe(el))}
async function refreshAll(){await refreshEscrowState();await refreshWalletUi();if(state.wallet){await scanWalletPusdc();await refreshMyEscrow()}}
async function boot(){bindReveal();bindUi();$('escrowAddr').textContent=CFG.ESCROW;await refreshEscrowState();await refreshWalletUi();setInterval(refreshEscrowState,25000)}
document.addEventListener('DOMContentLoaded',()=>boot().catch(e=>{console.error(e);toast('Init error: '+e.message,'err')}))
})();